name: MainDeployCI
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
        env:
          CI: false
          

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
        env:
          REACT_APP_API_KEY : ${{secrets.REACT_APP_API_KEY}}
          REACT_APP_SPREADSHEET_ID : ${{secrets.REACT_APP_SPREADSHEET_ID}}
          REACT_APP_CLIENT_EMAIL :  ${{secrets.REACT_APP_CLIENT_EMAI}}
          REACT_APP_PRIVATE_KEY : ${{secrets.REACT_APP_PRIVATE_KEY}}
      
        
